services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  wedding-photo-backend:
    build: .
    ports:
      - "${HOST_PORT-8739}:${PORT-8739}"
    volumes:
      - ./.env:/root/.env
      - ./media:/root/media
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=${REDIS_ADDR-redis:6379}
    restart: unless-stopped
